# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0d57d62dbadc43251dbb6cbb39ec378c65143439dbec61baf56371e76da9116ee7d114c2bc3cee681fa67f710de78bbc3e8db9bbde9f5501583f5d95f0c0cc1

test:
  secret_key_base: dd0c1da80cacdb0c169951ffb5e0650a7cd224c7c4e7648c16b4b18239bc08bc8d3be41d655defb24a6298d9dddace3f4b81791787133486e844dd57ed112a46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
